# Image: base-debian
FROM debian:10.0

######################
# RAILS DEPENDENCIES #
######################
user root

# System dependencies
RUN apt-get update &&   \
    apt-get install -y  \
                    vim \
                    sudo
RUN apt-get clean

